config/routes.rb
OpenProtocol::Application.routes.draw do
  match 'users/reset_password'         => "users#reset_password"
  match 'users/forgot_password'        => "users#forgot_password"
  resources :users
  resource :user_session
  get  'protocols/new'                => "protocols#new"
  post 'protocols/create'             => "protocols#create"
  get  'protocols/new_step'           => "protocols#new_step"
  get  'protocols/new_author'         => "protocols#new_author"
  get  'protocols/new_reagent'        => "protocols#new_reagent"
  post 'protocols/upload_image'       => "protocols#upload_image"
  post 'protocols/remove_image'       => "protocols#remove_image"
  post 'protocol/:id/vote'            => "protocols#vote"
  match 'protocol/:id/add_to_collection' => "protocols#add_to_collection"
  post 'protocol/:id/create_comment' => "protocols#create_comment"
  post 'protocol/:id/inline_edit'    => "protocols#inline_edit"
  post 'protocol/:id/remove_step'    => "protocols#remove_step"
  post 'protocol/:id/edit_step'      => "protocols#edit_step"
  get  'protocol/:id/*title'         => "protocols#show"
  get  'protocol/:id'                => "protocols#show"

  get  'collections/new'              => "collections#new"
  get  'collections/my'               => "collections#my", :as => "my_collections"
  post 'collection/create'            => "collections#create"
  post 'collections/remove_protocol'  => "collections#remove_protocol"
  post 'collections/rename_category'  => "collections#rename_category"
  post 'collection/:id/inline_edit'  => "collections#inline_edit"
  get  'collection/:id/category_autocomplete' => "collections#category_autocomplete"
  match 'collection/:id/delete'      => "collections#delete"
  get  'collection/:id'              => "collections#show"


  match 'users/forgot_password'        => "users#forgot_password"
  match 'about' => "homepage#about", :as => 'about'
  match 'login' => "user_sessions#new", :as => 'login'
  match 'logout' => "user_sessions#destroy", :as => 'logout'
  match 'register' => "users#new", :as => 'register'

  match 'search' => "search#new", :as => 'search'
  match 'feedback' => "homepage#feedback", :as => 'feedback'
  root :to => "homepage#index"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title openProtocol 0.1 BETA
    = stylesheet_link_tag 'reset', 'application', :media => 'all'
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery-ui.js'
    = javascript_include_tag 'facebox.js'
    = stylesheet_link_tag 'facebox.css'
    = stylesheet_link_tag 'jquery-ui.css'
    = csrf_meta_tag
    - if content_for?(:head)
      =  yield :head
  %body
    #feedback
      = link_to("Feedback", feedback_path)
    #header
      #logo
        %h1
          = link_to("openProtocol 0.1", root_path)
        %span#beta BETA
      #menu
        %ul
          %li
            - if current_user.try(:administrated_collections).try(:any?)
              = link_to "My Collections", :action => :my, :controller => :collections
          %li
            = link_to "Search", search_path
          %li#add_new_container
            = link_to "Add New", "javascript:void(0)", :id => "add_new"
            #add_new_sub_menu{:style => "display:none;"}
              = link_to "Protocol", :action => :new, :controller => :protocols
              = link_to "Collection", :action => :new, :controller => :collections
          %li
            = link_to "Language", "", :style => 'display:none;'
          %li
            - if current_user
              = link_to "Log Out", logout_path
            - else
              = link_to "Log In", login_path, :id => "login"
          %li
            = link_to "Register", register_path, :id => "register" unless current_user
    #content
      = yield
    #footer
      #footer_menu
        %ul
          %li
            = link_to "About Us", about_path
          %li
            = link_to "Blog", "http://openprotocol.tumblr.com/"
          %li
            = link_to "Contact", about_path
      = image_tag("cc_license.png", :id => "license")
      #license_text
        Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 3.0 License.
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-21248032-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();